require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/base_menus", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BaseMenu. As you add validations to BaseMenu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BaseMenu.create! valid_attributes
      get base_menus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      base_menu = BaseMenu.create! valid_attributes
      get base_menu_url(base_menu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_base_menu_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      base_menu = BaseMenu.create! valid_attributes
      get edit_base_menu_url(base_menu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BaseMenu" do
        expect {
          post base_menus_url, params: { base_menu: valid_attributes }
        }.to change(BaseMenu, :count).by(1)
      end

      it "redirects to the created base_menu" do
        post base_menus_url, params: { base_menu: valid_attributes }
        expect(response).to redirect_to(base_menu_url(BaseMenu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BaseMenu" do
        expect {
          post base_menus_url, params: { base_menu: invalid_attributes }
        }.to change(BaseMenu, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post base_menus_url, params: { base_menu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested base_menu" do
        base_menu = BaseMenu.create! valid_attributes
        patch base_menu_url(base_menu), params: { base_menu: new_attributes }
        base_menu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the base_menu" do
        base_menu = BaseMenu.create! valid_attributes
        patch base_menu_url(base_menu), params: { base_menu: new_attributes }
        base_menu.reload
        expect(response).to redirect_to(base_menu_url(base_menu))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        base_menu = BaseMenu.create! valid_attributes
        patch base_menu_url(base_menu), params: { base_menu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested base_menu" do
      base_menu = BaseMenu.create! valid_attributes
      expect {
        delete base_menu_url(base_menu)
      }.to change(BaseMenu, :count).by(-1)
    end

    it "redirects to the base_menus list" do
      base_menu = BaseMenu.create! valid_attributes
      delete base_menu_url(base_menu)
      expect(response).to redirect_to(base_menus_url)
    end
  end
end
